name: trend_py311
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py312haa95532_1
  - pip=25.3=pyhc872135_0
  - python=3.12.7=h14ffc60_0
  - setuptools=80.10.1=py312haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - joblib==1.5.3
      - lightgbm==4.6.0
      - numpy==1.26.4
      - pandas==2.3.3
      - pyarrow==16.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tzdata==2025.3
prefix: E:\Miniconda3\envs\trend_py311
